### ISSUE TITLE
Remove abstraction layer between repomate and PyGithub

### ISSUE THREAD

**Issue by slarse** [slarse/repomate#98]
Although I would rather use graphql, the API just doesn't have all of the features I need at this time.

**Comment by slarse** [comment]
This will be a MAJOR refactor.

**Comment by AnneTheAgile** [comment]
Do I read correctly this means : "Closed, will not do"?

**Comment by slarse** [comment]
@AnneTheAgile Hi! No, this has been implemented, was closed as of e0e7a1b
